package NA.Compu_Na;
import NA.Compu_Na.Common.*;

public class NonminingPools_20_Percent {
    public static void main(String [] args){
    	System.out.println("Type:NonPools(%20) Confirm_Number:8");
//        MutliThread m1=new MutliThread("Window 1");
//        MutliThread m2=new MutliThread("Window 2");
//        MutliThread m3=new MutliThread("Window 3");
        MutliThread1 M1=new MutliThread1("USER_1","Honest_Node");
        MutliThread1 M2=new MutliThread1("USER_2","Honest_Node");
        MutliThread1 M3=new MutliThread1("USER_3","Honest_Node");
        MutliThread1 M4=new MutliThread1("USER_4","Malicious_Node");
        MutliThread1 M5=new MutliThread1("USER_5","Malicious_Node");
        MutliThread1 M6=new MutliThread1("USER_6","Honest_Node");
        MutliThread1 M7=new MutliThread1("USER_7","Honest_Node");
        MutliThread1 M8=new MutliThread1("USER_8","Honest_Node");
        MutliThread1 M9=new MutliThread1("USER_9","Honest_Node");
        MutliThread1 M10=new MutliThread1("USER_10","Honest_Node");
        MutliThread1 M11=new MutliThread1("USER_11","Honest_Node");
        MutliThread1 M12=new MutliThread1("USER_12","Honest_Node");
        MutliThread1 M13=new MutliThread1("USER_13","Honest_Node");
        MutliThread1 M14=new MutliThread1("USER_14","Malicious_Node");
        MutliThread1 M15=new MutliThread1("USER_15","Malicious_Node");
        MutliThread1 M16=new MutliThread1("USER_16","Honest_Node");
        MutliThread1 M17=new MutliThread1("USER_17","Honest_Node");
        MutliThread1 M18=new MutliThread1("USER_18","Honest_Node");
        MutliThread1 M19=new MutliThread1("USER_19","Honest_Node");
        MutliThread1 M20=new MutliThread1("USER_20","Honest_Node");
        MutliThread1 M21=new MutliThread1("USER_21","Honest_Node");
        MutliThread1 M22=new MutliThread1("USER_22","Honest_Node");
        MutliThread1 M23=new MutliThread1("USER_23","Honest_Node");
        MutliThread1 M24=new MutliThread1("USER_24","Malicious_Node");
        MutliThread1 M25=new MutliThread1("USER_25","Malicious_Node");
        MutliThread1 M26=new MutliThread1("USER_26","Honest_Node");
        MutliThread1 M27=new MutliThread1("USER_27","Honest_Node");
        MutliThread1 M28=new MutliThread1("USER_28","Honest_Node");
        MutliThread1 M29=new MutliThread1("USER_29","Honest_Node");
        MutliThread1 M30=new MutliThread1("USER_30","Honest_Node");
        MutliThread1 M31=new MutliThread1("USER_31","Honest_Node");
        MutliThread1 M32=new MutliThread1("USER_32","Honest_Node");
        MutliThread1 M33=new MutliThread1("USER_33","Honest_Node");
        MutliThread1 M34=new MutliThread1("USER_34","Malicious_Node");
        MutliThread1 M35=new MutliThread1("USER_35","Malicious_Node");
        MutliThread1 M36=new MutliThread1("USER_36","Honest_Node");
        MutliThread1 M37=new MutliThread1("USER_37","Honest_Node");
        MutliThread1 M38=new MutliThread1("USER_38","Honest_Node");
        MutliThread1 M39=new MutliThread1("USER_39","Honest_Node");
        MutliThread1 M40=new MutliThread1("USER_40","Honest_Node");
        MutliThread1 M41=new MutliThread1("USER_41","Honest_Node");
        MutliThread1 M42=new MutliThread1("USER_42","Honest_Node");
        MutliThread1 M43=new MutliThread1("USER_43","Honest_Node");
        MutliThread1 M44=new MutliThread1("USER_44","Malicious_Node");
        MutliThread1 M45=new MutliThread1("USER_45","Malicious_Node");
        MutliThread1 M46=new MutliThread1("USER_46","Honest_Node");
        MutliThread1 M47=new MutliThread1("USER_47","Honest_Node");
        MutliThread1 M48=new MutliThread1("USER_48","Honest_Node");
        MutliThread1 M49=new MutliThread1("USER_49","Honest_Node");
        MutliThread1 M50=new MutliThread1("USER_50","Honest_Node");
        MutliThread1 M51=new MutliThread1("USER_51","Honest_Node");
        MutliThread1 M52=new MutliThread1("USER_52","Honest_Node");
        MutliThread1 M53=new MutliThread1("USER_53","Honest_Node");
        MutliThread1 M54=new MutliThread1("USER_54","Malicious_Node");
        MutliThread1 M55=new MutliThread1("USER_55","Malicious_Node");
        MutliThread1 M56=new MutliThread1("USER_56","Honest_Node");
        MutliThread1 M57=new MutliThread1("USER_57","Honest_Node");
        MutliThread1 M58=new MutliThread1("USER_58","Honest_Node");
        MutliThread1 M59=new MutliThread1("USER_59","Honest_Node");
        MutliThread1 M60=new MutliThread1("USER_60","Honest_Node");
        MutliThread1 M61=new MutliThread1("USER_61","Honest_Node");
        MutliThread1 M62=new MutliThread1("USER_62","Honest_Node");
        MutliThread1 M63=new MutliThread1("USER_63","Honest_Node");
        MutliThread1 M64=new MutliThread1("USER_64","Malicious_Node");
        MutliThread1 M65=new MutliThread1("USER_65","Malicious_Node");
        MutliThread1 M66=new MutliThread1("USER_66","Honest_Node");
        MutliThread1 M67=new MutliThread1("USER_67","Honest_Node");
        MutliThread1 M68=new MutliThread1("USER_68","Honest_Node");
        MutliThread1 M69=new MutliThread1("USER_69","Honest_Node");
        MutliThread1 M70=new MutliThread1("USER_70","Honest_Node");
        MutliThread1 M71=new MutliThread1("USER_71","Honest_Node");
        MutliThread1 M72=new MutliThread1("USER_72","Honest_Node");
        MutliThread1 M73=new MutliThread1("USER_73","Honest_Node");
        MutliThread1 M74=new MutliThread1("USER_74","Malicious_Node");
        MutliThread1 M75=new MutliThread1("USER_75","Malicious_Node");
        MutliThread1 M76=new MutliThread1("USER_76","Honest_Node");
        MutliThread1 M77=new MutliThread1("USER_77","Honest_Node");
        MutliThread1 M78=new MutliThread1("USER_78","Honest_Node");
        MutliThread1 M79=new MutliThread1("USER_79","Honest_Node");
        MutliThread1 M80=new MutliThread1("USER_80","Honest_Node");
        MutliThread1 M81=new MutliThread1("USER_81","Honest_Node");
        MutliThread1 M82=new MutliThread1("USER_82","Honest_Node");
        MutliThread1 M83=new MutliThread1("USER_83","Honest_Node");
        MutliThread1 M84=new MutliThread1("USER_84","Malicious_Node");
        MutliThread1 M85=new MutliThread1("USER_85","Malicious_Node");
        MutliThread1 M86=new MutliThread1("USER_86","Honest_Node");
        MutliThread1 M87=new MutliThread1("USER_87","Honest_Node");
        MutliThread1 M88=new MutliThread1("USER_88","Honest_Node");
        MutliThread1 M89=new MutliThread1("USER_89","Honest_Node");
        MutliThread1 M90=new MutliThread1("USER_90","Honest_Node");
        MutliThread1 M91=new MutliThread1("USER_91","Honest_Node");
        MutliThread1 M92=new MutliThread1("USER_92","Honest_Node");
        MutliThread1 M93=new MutliThread1("USER_93","Honest_Node");
        MutliThread1 M94=new MutliThread1("USER_94","Malicious_Node");
        MutliThread1 M95=new MutliThread1("USER_95","Malicious_Node");
        MutliThread1 M96=new MutliThread1("USER_96","Honest_Node");
        MutliThread1 M97=new MutliThread1("USER_97","Honest_Node");
        MutliThread1 M98=new MutliThread1("USER_98","Honest_Node");
        MutliThread1 M99=new MutliThread1("USER_99","Honest_Node");
        MutliThread1 M100=new MutliThread1("USER_100","Honest_Node");
//        m1.start();
//        m2.start();
//        m3.start();
        M1.start();
        M2.start();
        M3.start();
        M4.start();
        M5.start();
        M6.start();
        M7.start();
        M8.start();
        M9.start();
        M10.start();
        M11.start();
        M12.start();
        M13.start();
        M14.start();
        M15.start();
        M16.start();
        M17.start();
        M18.start();
        M19.start();
        M20.start();
        M21.start();
        M22.start();
        M23.start();
        M24.start();
        M25.start();
        M26.start();
        M27.start();
        M28.start();
        M29.start();
        M30.start();
        M31.start();
        M32.start();
        M33.start();
        M34.start();
        M35.start();
        M36.start();
        M37.start();
        M38.start();
        M39.start();
        M40.start();
        M41.start();
        M42.start();
        M43.start();
        M44.start();
        M45.start();
        M46.start();
        M47.start();
        M48.start();
        M49.start();
        M50.start();
        M51.start();
        M52.start();
        M53.start();
        M54.start();
        M55.start();
        M56.start();
        M57.start();
        M58.start();
        M59.start();
        M60.start();
        M61.start();
        M62.start();
        M63.start();
        M64.start();
        M65.start();
        M66.start();
        M67.start();
        M68.start();
        M69.start();
        M70.start();
        M71.start();
        M72.start();
        M73.start();
        M74.start();
        M75.start();
        M76.start();
        M77.start();
        M78.start();
        M79.start();
        M80.start();
        M81.start();
        M82.start();
        M83.start();
        M84.start();
        M85.start();
        M86.start();
        M87.start();
        M88.start();
        M89.start();
        M90.start();
        M91.start();
        M92.start();
        M93.start();
        M94.start();
        M95.start();
        M96.start();
        M97.start();
        M98.start();
        M99.start();
        M100.start();
    }
}